name: "Example Composite Action"
description: "An example composite action"
inputs:
  token:
    description: "token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Print environment variable
      run: echo "${{ inputs.token }}"
      shell: bash
