name: "Example Composite Action"
description: "An example composite action"
inputs:
  token:
    description: "token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Print environment variable
      run:  |
        echo "${{ inputs.token }}"
        git config --global url."https://${{ inputs.token_github }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        git clone --branch main https://github.com/muhammedgamal760/grad_project.git
